name: ðŸš€ Do tag.
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name (e.g. release/3.3.0)'
        required: true
      tag:
        description: 'Tag name (e.g., v3.3.1)'
        required: true

jobs:
  do-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Switch to the branch and create a tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch origin "${{ github.event.inputs.branch }}"
          git fetch -p -P -t -f
          git checkout "${{ github.event.inputs.branch }}"
          git tag "${{ github.event.inputs.tag }}"
          git push origin "${{ github.event.inputs.tag }}"
